[package]
name = "bioinfo-algos"
version = "0.1.0"
authors = ["jason"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.8", features = ["macros"] }
structopt = { version = "0.3" }
